---
title: "Metadata"
output:
  html_document:
    toc: TRUE
    toc_depth: 3
    toc_float:
        collapsed: FALSE
---

<div class = "definition">
**Metadata is an umbrella term involving all the ways in which you may describe your data, including discovery, access and use by others. Put simply, it is \"Data about data\".**

This is new content.

Metadata is a way to help describe and enhance the re-usability of your data.
</div>

<hr />

<div class = "consideration">
**Key Notes**

Meta data is part of the documentation of your research. It is also helpful when your metadat adheres to relevant standards. So, when planning and managing your research, you should also consider:

* Metadata standards.  [Read more about metadata standards](p_metadata-standards.html).
* Data documentation.  [Read more about data documentation](p_documention.html).

As always, if you are unsure about any of the above, or have questions, [get in touch](s_talk.html). 
</div>

## Types of Metadata

Metadata comes in three basic flavours, depending on what aspect of a research project we\'re trying to describe. Each will potentially have it\'s own standard, depending on your field of practice.

### > Descriptive

Information about the content and context of your data.

Examples: title, creator, keywords, descriptions

### > Structural

Information about how different data sets relate to one another, or any processing or formatting steps that were undertaken.

Examples: instruments used, file formats, indexes

### > Administrative

Information about instructions, rules, and restrictions about your data.

Examples: access controls and use requirements, copyright permissions, acquisition information